apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnpl-dispatcher-service
  labels:
    app: bnpl-dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnpl-dispatcher-service
  template:
    metadata:
      labels:
        app: bnpl-dispatcher-service
    spec:
      containers:
        - name: bnpl-dispatcher-service
          image: bnpl-dispatcher-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://bnpl-config-service
            - name: SPRING_RABBITMQ_HOST
              value: bnpl-rabbitmq
