apiVersion: v1
kind: Service
metadata:
  name: bnpl-dispatcher-service
  labels:
    app: bnpl-dispatcher-service
spec:
  type: ClusterIP
  selector:
    app: bnpl-dispatcher-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9003
